### ISSUE TITLE
how to use timestamp without timezone

### ISSUE THREAD

**Issue by araneta** [ngs-doo/dsl-compiler-client#115]
how to use timestamp without timezone ? is that possible
```
root Requirement{
		string name;
		bool isActive;
		ScholarshipType *ScholarshipType;
		bool forSurvey;
		int inputType; //1: file, 2:text
		bool mandatory;
timestamp? createdAt;
timestamp? updatedAt;
timestamp? deletedAt;
	}
```

**Comment by zapov** [comment]
Timestamp without TZ is almost always the wrong type to use in PG.
PG doesn't even save the TZ as it was specified, but it rather converts it to instance configured one.

If for some reason you really need TS without TZ you can use two fields: Date and Time

**Comment by araneta** [comment]
i see, thank you so much for your explanation
