### ISSUE TITLE
Compilation with -apply and without -migration in 1.2.1

### ISSUE THREAD

**Issue by dstimac** [ngs-doo/dsl-compiler-client#41]
Ends with message:
  "Can't find SQL migration file. Unable to apply database migration."
In previous versions this worked.
Help says: 
 "-apply                  Apply migration on the database after creating the migration script"
Implicitly set -migration when -apply is set?

**Comment by zapov** [comment]
Fixed in commit 6e67770bed721387d5d8b45febfdc3b312a1d7df
