### ISSUE TITLE
Cosmetic DSL changes should produce database migration scripts

### ISSUE THREAD

**Issue by melezov** [ngs-doo/dsl-compiler-client#56]
When migrating:

    module foo {
      aggregate Bar {
        String a;
        Int b;
      }
    }

into

    module foo {
      aggregate Bar {
        Int b;     // This is user ID
        String a; // This is user token
      }
    }

A migration script will not be created, so when inspecting the next migration diff it may be confusing.
Also, it's a good feature to have the latest DSL in the database in case one needs to revert and the model was lost.

**Comment by zapov** [comment]
Fixed
