### ISSUE TITLE
dsl-clc should pass relative DSL paths to dsl-compiler

### ISSUE THREAD

**Issue by melezov** [ngs-doo/dsl-compiler-client#58]
Currently, it is sending platform-dependent file paths such as:

    r:\a\dsl\a.dsl
    /home/melezov/foo/model/foo.dsl

This puts the absolute paths in the SQL migration script, where it should be relative, and platform-independent:

    dsl/a.dsl
    model/foo.dsl

dsl-compiler works with / as path separator on Windows, so replacing \ with / should work

**Comment by zapov** [comment]
Fixed.
