### ISSUE TITLE
dsl-clc.properties resource should be updated when packaging

### ISSUE THREAD

**Issue by melezov** [ngs-doo/dsl-compiler-client#60]
Investigate something like [sbt-buildinfo](https://github.com/sbt/sbt-buildinfo) for Maven, to automatically update the version numbers in [dsl-clc.properties](https://github.com/ngs-doo/dsl-compiler-client/blob/master/CommandLineClient/src/main/resources/com/dslplatform/compiler/client/dsl-clc.properties)

**Comment by zapov** [comment]
No, dsl-clc should be removed :/

**Comment by zapov** [comment]
Fixed.
