### ISSUE TITLE
Connect to db using ssh

### ISSUE THREAD

**Issue by araneta** [ngs-doo/dsl-compiler-client#72]
is it possible to connect to db host using Standard TCP/IP over SSH, using ssh key file? please give me some examples
Thanks

**Comment by zapov** [comment]
it should be possible although I never tried it myself. It uses pgjdbc and it supports it via ssl=true.
Maybe this will help: http://serverfault.com/questions/627169/how-to-secure-an-open-postgresql-port and https://jdbc.postgresql.org/documentation/93/ssl-client.html

**Comment by araneta** [comment]
ok thanks i can solve this using port forwarding
