### ISSUE TITLE
accidentally remove a table

### ISSUE THREAD

**Issue by araneta** [ngs-doo/dsl-compiler-client#79]
I accidentally remove a table, when i try to generate migration script it shows this error message:
ERROR: relation "university.CoursePackageCourses" does not exist
  Where: SQL statement "ALTER TABLE "university"."CoursePackageCourses" ADD COLUMN "CourseSchedulledID" INT"
PL/pgSQL function inline_code_block line 3 at SQL statement
What should i do to fix this?
Thanks

**Comment by zapov** [comment]
You mean you've removed CoursePackageCourses ?
You can truncate "-DSL-".database_migration
It will rebuild everything from scratch then (this should work most of the time)

**Comment by araneta** [comment]
Thanks its working

**Comment by araneta** [comment]
the table is recreated but the ID is not using sequence number like other table? what should i do?
right now the id column definition is:
"ID" integer NOT NULL, -- NGS generated

**Comment by araneta** [comment]
i deleted the sequences and truncated the migration table and its working now
