### ISSUE TITLE
Bug: Visual Studio plugin does not save POCO settings to .sln

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/dsl-compiler-client#80]
Seems like the VS plugin does not save the POCO settings to the .sln file.

Complete the POCO settings, check the checkbox, save the solution, close VS, open VS and the POCO is unchecked and my POCO settings are gone.

I'll try to fix the bug in the plugin when I have some time.

My current workaround is to restore my a copy of the .sln file with the POCO settings before I open the solution.

For example:

```
Microsoft Visual Studio Solution File, Format Version 12.00
...
Global
	GlobalSection(DslPlatformSolutionProperties) = preSolution
...
		Postgres.Compile = True
...
		Poco.Compile = True
		Poco.Name = UseCase1.DSL.Common
		Poco.Target = Common\Lib\Revenj
		Poco.Dependencies = Common\Lib\Revenj\POCO
		Poco.UseUtc = True
...
	EndGlobalSection
EndGlobal

```

**Comment by zapov** [comment]
Tnx for the bug report.

It's fixed in latest commit. Can you build new version yourself?

**Comment by Kobus-Smit** [comment]
Thanks @zapov 
I get 3 errors when I build it in VS2017, all of them are:
Cannot find the type 'VsBrushes' in DiffPlexControl.xaml etc.

Don't know if it is a VS version issue?

**Comment by zapov** [comment]
I usually use VS 2010 to build it, although I did try VS 2017 just now and it did build.
But it's probable that the plugin is referencing something which doesn't exists in newer versions of VS.

I pushed the new plugin with this fix to the marketplace.

**Comment by Kobus-Smit** [comment]
Thank you @zapov !

I got the latest plugin from the marketplace and modified extension.vsixmanifest to install into into VS 2017.
