### ISSUE TITLE
Parse/Compile unsaved dsl in Visual Studio Plugin

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/dsl-compiler-client#89]
Low priority suggestion: 

Although the .dsl file are parsed in real-time and can show errors as we type, the Parse and Compile buttons requires the .dsl file to be saved.

Some times I forget to save the .dsl file and press Compile and the plugin compiles the saved .dsl while I intuitively expected it to compile my latest changes. I think this might happen to other users too.

Would it be possible for those buttons to rather parse/compile the current unsaved dsl?

Or otherwise give me some kind of indication or prompt me to first optionally save the changes before continuing compilation?

**Comment by zapov** [comment]
MessageBox that the files are not saved certainly sounds good (with an option to save and compile them or cancel the compilation)

**Comment by Kobus-Smit** [comment]
Sounds good!

**Comment by Kobus-Smit** [comment]
I've noticed this is not an issue for me anymore because I'm using the "Auto save when document loses focus" feature of the [Tweaks](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Tweaks2022#autosave) extension
