### ISSUE TITLE
Option to hide or delay tooltips in Visual Studio Plugin

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/dsl-compiler-client#90]
Low priority suggestion for a minor but constant irritation :smile:

The tooltips pops up immediately and while it was useful in the beginning I now found them to be a distraction. 

![Alt Text](https://github.com/Kobus-Smit/revenj-examples/raw/master/tmp/tooltips.gif)

And they sometimes obstruct the status message:
![image](https://user-images.githubusercontent.com/11263864/36570400-fc5b2532-1885-11e8-84f3-4a33229a5a66.png)

Would it be possible to provide a user preference (or .config entry) to enable/disable the tooltips or change the initial delay to for example 3 seconds rather than showing it immediately?

I've added it to my backlog and when I have some time for this I'll submit a PR.

**Comment by zapov** [comment]
The parse tooltip is not even correct ;)

3 seconds sounds too long, 1 second seems better to me?

I don't have anything against the configs, although I think a better solution would be to make those two buttons globally accessible from VS so you can use keyboard shortcuts to invoke them instead of mouse clicking them all the time

Btw, if you right click in the content of the dsl file you should get a popup with compile option

**Comment by Kobus-Smit** [comment]
Yeah that tooltip text sounds a bit overpromising... 🤣 

1 sec would be a better smart default yes.

But it will still pop up in my work flow :)
because I found I click Parse button and then immediately move my mouse cursor to the Compile button while I wait for the Parsing to succeed/fail and then click Compile. So the huge Compile tooltip would popup after 1 sec and obscure the Parsing label ;)

Too many user prefs are not good and changing config files is not that friendly (although it might be ok for not so common or advanced options)

What about a little :gear: dropdown icon which drops down a menu where the user can then check or uncheck Show tooltips?

I'd like the keyboard shortcuts and would use them.

I've only noticed the right click, Compile DSL menu item now ;)  
It's a few ms more effort to click it compared to the Compile button that I have in a visible docked panel, though it is certainly more useful when DSL Platform panel is not visible. 
It is also quite easy to use via the Windows App Key, Up Arrow, Enter combination. 
Compiling via that menu option however does not give the user any visual indication if he had the DSL Platform panel closed or not active. Showing the compilation status in VS's status bar might be handy then.

**Comment by Kobus-Smit** [comment]
I had a quick look at [disabling tooltips](https://stackoverflow.com/questions/49411130/enable-disable-tooltips-for-all-controls-in-wpf-app). 

We'd need a config file to save the "Show tooltips" setting (would not make sense to save it in the .sln file where the other settings are saved, because it is not solution specific)

Closing issue it for now because now sure if this is worth implementing.
