### ISSUE TITLE
Add an API as an alternative to reading the previous DSL from the database

### ISSUE THREAD

**Issue by melezov** [ngs-doo/dsl-compiler-client#91]
Currently, the only way to perform a migration is to read the recent migration file from the database.

Add a way to supply the old migration programatically (e.g. as a Map<String, String>) so that migration generation can be integrated more seamlessly (e.g. by reading the old DSL from Git history or from another folder)

**Comment by zapov** [comment]
Fixed in v1.9.5 via previous-sql:db parameter
